In [ ]:
# Load statistical unit (the shapefile of LSOA of London)
lsoa_gdf = gpd.read_file('../GIS_file/LSOA_2011_London_gen_MHW.shp')

# load Santander bike trip destination data for cluster0 and cluster1
endpoints0 = gpd.read_file('../GIS_file/end_points0.geojson')
endpoints1 = gpd.read_file('../GIS_file/end_points1.geojson')
endpointsALL = gpd.read_file('../GIS_file/end_pointsALL.geojson')

# imput polygon data
retail = gpd.read_file('../GIS_file/POI/landuse_retail.shp')
commercial = gpd.read_file('../GIS_file/POI/landuse_commercial1.shp')
residential = gpd.read_file('../GIS_file/POI/landuse_resident.shp')

leisurepark = gpd.read_file('../GIS_file/POI/leisure_park.shp')
water = gpd.read_file('../GIS_file/water.geojson')

# imput point data
office = gpd.read_file('../GIS_file/POI/office.shp')

# catering = Food, Drink and Multi Item Retail

school = gpd.read_file('../GIS_file/POI/school.shp')
tourism = gpd.read_file('../GIS_file/POI/tourism4.shp')
bus = gpd.read_file('../GIS_file/POI/bus.shp')
railway = gpd.read_file('../GIS_file/POI/railway_station.shp')
subway = gpd.read_file('../GIS_file/POI/subway_entrance1.shp')
PnR_spaces = gpd.read_file('../3.access/cycleparking_point.geojson')

# imput road network data
roadnet = gpd.read_file('../GIS_file/road_network/roadnet_santander.shp') # polyline
roadjuctions = gpd.read_file('../GIS_file/road_network/roadnet_santander_ND_Junctions.shp') # point data

In [4]:
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point

In [7]:
poi = pd.read_csv('../GIS_file/POI/all_poi2023.csv')
# bus = pd.read_csv('./CSV版本/交通设施服务.csv',encoding='gbk')
# residential = pd.read_csv('./CSV版本/商务住宅.csv',encoding='gbk')
# catering = pd.read_csv('./CSV版本/餐饮.csv',encoding='gbk')
# shopping = pd.read_csv('./CSV版本/购物.csv',encoding='gbk')
# company = pd.read_csv('./CSV版本/公司企业.csv',encoding='gbk')
# entertainment = pd.read_csv('./CSV版本/体育休闲服务.csv',encoding='gbk')
# residential = residential[(residential['中类']=='住宅区')]
# company = company[(company['中类']=='公司')|(company['中类']=='公司企业')]
#bus = bus[bus['Category']=='公交车站']

poi.head(2)

,id,ref_no,name,pointx_class,groupname,categoryname,classname,feature_easting,feature_northing,pos_accuracy,...,geographic_county,postcode,admin_boundary,telephone_number,url,brand,qualifier_type,qualifier_data,provenance,supply_date
0,1,63875672,Allotment Gardens,6340453,Public Infrastructure,Infrastructure and Facilities,Allotments,535647.0,174221.0,1,...,Greater London,SE23,Southwark London Boro,NaN,NaN,NaN,NaN,NaN,Ordnance Survey,2023/12/01
1,2,63875684,Allotment Gardens,6340453,Public Infrastructure,Infrastructure and Facilities,Allotments,536592.0,173647.0,1,...,Greater London,SE6,Lewisham London Boro,NaN,NaN,NaN,NaN,NaN,Ordnance Survey,2023/12/01

In [8]:
catering = poi[poi['categoryname']== 'Food, Drink and Multi Item Retail']
catering.head(2)

,id,ref_no,name,pointx_class,groupname,categoryname,classname,feature_easting,feature_northing,pos_accuracy,...,geographic_county,postcode,admin_boundary,telephone_number,url,brand,qualifier_type,qualifier_data,provenance,supply_date
13009,13010,47971276,Belle Epoque Patisserie,9470661,Retail,"Food, Drink and Multi Item Retail",Bakeries,532882.0,185437.0,1,...,Greater London,N16 9PR,Hackney London Boro,2.072492e+09,NaN,NaN,NaN,NaN,118 Information,2023/12/01
13200,13201,47979425,Kensington Court Cafe Ltd,9470661,Retail,"Food, Drink and Multi Item Retail",Bakeries,525798.0,179521.0,1,...,Greater London,W8 5ET,Kensington and Chelsea London Boro,2.073762e+09,NaN,NaN,NaN,NaN,118 Information,2023/12/01

In [9]:
# 将 DataFrame 转换为 GeoDataFrame
geometry = [Point(xy) for xy in zip(catering['feature_easting'], catering['feature_northing'])]
catering1 = gpd.GeoDataFrame(catering, geometry=geometry)

# 设置坐标参考系统为 OSGB36 (EPSG:27700)
catering1.crs = 'epsg:27700'

# 查看创建的 GeoDataFrame
catering1.head(1)

,id,ref_no,name,pointx_class,groupname,categoryname,classname,feature_easting,feature_northing,pos_accuracy,...,postcode,admin_boundary,telephone_number,url,brand,qualifier_type,qualifier_data,provenance,supply_date,geometry
13009,13010,47971276,Belle Epoque Patisserie,9470661,Retail,"Food, Drink and Multi Item Retail",Bakeries,532882.0,185437.0,1,...,N16 9PR,Hackney London Boro,2.072492e+09,NaN,NaN,NaN,NaN,118 Information,2023/12/01,POINT (532882.000 185437.000)

In [ ]:
 # Daily essential shopping & grocery :including alcoholic beverages, green and new age products, bakery goods, fresh produce, 
# meat products, herbs and spices, livestock, confectionery, groceries, 
# organic and gourmet foods, deli items, tea and coffee, frozen foods, and other convenience items.


catering = poi[poi['categoryname']== 'Food, Drink and Multi Item Retail']
catering.head(2)

In [ ]:
catering = poi[poi['categoryname']== 'Food, Drink and Multi Item Retail']
catering.head(2)
# 保存为GeoJSON文件
catering1.to_file("../GIS_file/POI/catering.geojson", driver='GeoJSON')

In [ ]:


### 去除文件中缺失信息
poi = [bus.copy(),catering.copy(),company.copy(),residential.copy(),shopping.copy(),entertainment.copy()]
for i in range(len(poi)):
    poi[i].dropna(inplace=True)

In [ ]:


### 去除文件中缺失信息
poi = [bus.copy(),catering.copy(),company.copy(),residential.copy(),shopping.copy(),entertainment.copy()]
for i in range(len(poi)):
    poi[i].dropna(inplace=True)
    
    
def point(arr):
    return Point(arr['long'],arr['lat']) ## 定义转换函数
for i in range(len(poi)):
    poi[i]['geometry'] = poi[i].apply(point,axis=1) #识别经纬度，转换点数据
    poi[i] = gpd.GeoDataFrame(poi[i])
    poi[i].crs = {'init':'epsg:27700'}     ### 设置坐标系为wgs84
for i in range(len(poi)):
    poi[i] = gpd.sjoin(poi[i],area,op='within',how='left')
    poi[i].dropna(inplace=True)   ### 进行空间连接 将poi连接到相应格子
    
### 开始计算格子内各类poi的数量
stat = area.loc[:,['index']]
for x in range(len(poi)):
        stat = pd.merge(stat,poi[x].groupby('index')['名称'].count().to_frame().reset_index(),on='index',how='outer')
stat.columns = ['index','bus','catering','company','residential','shopping','entertainment']
stat.fillna(0,inplace=True) ### 填充缺失值



### 计算土地利用混合度
stat['landuse_mix'] = 0
for i in range(len(stat)):
    total = 0
    for x in range(1,7):
        total += stat.iloc[i,x]
    for x in range(1,7):
        if total == 0:   ### 有的网格里面一个poi也没有，把他的混合度定为1
            stat.loc[i,'landuse_mix'] = 1
        else:
            stat.loc[i,'landuse_mix'] += (stat.iloc[i,x]/total)**2
stat.describe().T

All initial variable measures are straightforward except for the "land-use mix". 
The Herfindahl-Hirschman index (HHl) is widely used to measure industry concentration in economics, and inaddition, it can be used to reflect diversity. Therefore, this paper chose the HHl to represent'land-use mix". The calculation formula of the HHl is shown in Equation (1). A small HHl valueindicates a greater mixability, and vice versa.

In [ ]:

### 计算土地利用混合度
stat['landuse_mix'] = 0
for i in range(len(stat)):
    total = 0
    for x in range(1,7):
        total += stat.iloc[i,x]
    for x in range(1,7):
        if total == 0:   ### 有的网格里面一个poi也没有，把他的混合度定为1
            stat.loc[i,'landuse_mix'] = 1
        else:
            stat.loc[i,'landuse_mix'] += (stat.iloc[i,x]/total)**2
stat.describe().T